repos:
  - repo: local
    hooks:
      - id: ruff-linter
        name: ruff-linter
        entry: ruff check --fix
        language: system
        types: [ python ]
        exclude: ^(migrations/|settings/)

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [ python ]
        exclude: ^(migrations/|settings/)

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --config-file=./mypy.ini --explicit-package-bases .
        language: system
        types: [ python ]
        require_serial: true
