version: '3.7'
services:

  db:
    image: postgres:16-bullseye
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "54321:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ="GMT+3"
      - PGTZ="GMT+3"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s
  
  storage:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z.fips
    container_name: storage
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${AWS_S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_S3_SECRET_ACCESS_KEY}
    command: server --console-address ":9001" /data

  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - .env
    ports:
      - "6380:${REDIS_PORT}"
    command: redis-server
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      target: development
    container_name: backend
    hostname: backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/home/code
    entrypoint: > 
      bash -c "
        python3 manage.py init_bucket
        python3 manage.py collectstatic --noinput
        python3 manage.py migrate
        gunicorn settings.wsgi:application --bind=0.0.0.0:8000 --reload --timeout=0
      "
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  minio_storage:
  redis_data: