
exclude = [
    "migrations",
    "settings.py",
    "manage.py",
]

line-length = 99
target-version = "py311"
show-fixes = true
unsafe-fixes = true

[lint]
select = [
    "A", # Check for python builtins being used as variables or parameters. (flake8-builtins)
    "E", # check your Python code against some of the style conventions in PEP 8. (pycodestyle)
    "F", # source files for errors (Pyflakes)
    "ISC", # problems like implicitly concatenated string literals on the same line (flake8-implicit-str-concat)
    "I", # isort
    "N", # pep naming (pep8-naming)
    "PIE", # lints to warn about code that assigns and then immediately returns the assignment. (flake8-pie)
    "T20", # Check for Print statements in python files. (flake8-print)
    "RET", # plugin that checks return values. (flake8-return)
    "SLF", # Private member accessed (flake8-self)
    "SIM", # plugin that helps you simplify your code. (flake8-simplify)
    "ARG", # unused-arguments (flake8-unused-arguments)
    "ERA", # helps cleans up existing junk comments (eradicate)
    "PL", # static code analizer (pylint)
]
ignore = [
    "SIM117", # Add from __future__ import annotations
    "N812",
    ]

[format]
quote-style = "double"
# отдельные строки на каждый аргумент
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-line-length = 80

[lint.flake8-unused-arguments]
# Whether to allow unused variadic arguments, like *args and **kwargs.
ignore-variadic-names = true

[lint.isort]
case-sensitive = true
# сортировка не зависимо от стиля импота
force-sort-within-sections = true
lines-after-imports = 2
# сортировка по длинне
relative-imports-order = "closest-to-furthest"
known-first-party = ["core"]

[lint.pylint]
# Maximum number of arguments allowed for a function or method definition
max-args = 12
