
exclude = [
    "migrations",
    "settings.py",
    "manage.py",
]

line-length = 99
target-version = "py311"
show-fixes = true
unsafe-fixes = true

[lint]
select = [
    "A",
    "E",
    "F",
    "ISC",
    "I",
    "N",
    "PIE",
    "T20",
    "RET",
    "SLF",
    "SIM",
    "ARG",
    "ERA",
    "PL",
]
ignore = [
    "SIM117",
    "N812",
]

[format]
quote-style = "double"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-line-length = 80

[lint.flake8-unused-arguments]
ignore-variadic-names = true

[lint.isort]
case-sensitive = true
force-sort-within-sections = true
lines-after-imports = 2
relative-imports-order = "closest-to-furthest"
known-first-party = ["core", "users"]

[lint.pylint]
max-args = 12
